version: '3'

services:

  app:
    container_name: docker-weblocation
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    restart: unless-stopped
    depends_on: 
      - redis 
    command: ["go", "run", "main.go"]
    environment: 
      MAXMIND_KEY: ${MAXMIND_KEY}
      WEATHER_KEY: ${WEATHER_KEY}
      REDIS_URL: localhost:6379
    networks:
      - backend

  redis:
    image: "redis:alpine"    
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:    